version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rowin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teamstasts_development

networks:
  default:
    name: teamstats
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.69.0/24
