export const tableLoadingData = [
    {
        Rank: 1,
        Punten: 5,
        Naam: 'Rowin Kučera',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'ShortHairShortFlat',
            accessoriesType: 'Sunglasses',
            hatColor: 'Black',
            hairColor: 'Brown',
            facialHairType: 'BeardLight',
            facialHairColor: 'Brown',
            clotheType: 'Hoodie',
            clotheColor: 'Black',
            graphicType: 'Bat',
            eyeType: 'Happy',
            eyebrowType: 'Default',
            mouthType: 'Smile',
            skinColor: 'Tanned',
        },
    },
    {
        Rank: 2,
        Punten: 3,
        Naam: 'Thulani Aminu',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'LongHairFro',
            accessoriesType: 'Blank',
            hatColor: 'Red',
            hairColor: 'Red',
            facialHairType: 'MoustacheFancy',
            facialHairColor: 'Platinum',
            clotheType: 'Overall',
            clotheColor: 'Blue01',
            graphicType: 'Bear',
            eyeType: 'Default',
            eyebrowType: 'RaisedExcitedNatural',
            mouthType: 'ScreamOpen',
            skinColor: 'Light',
        },
    },
    {
        Rank: 3,
        Punten: 3,
        Naam: 'Sunil Ríos',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'ShortHairTheCaesarSidePart',
            accessoriesType: 'Blank',
            hatColor: 'Black',
            hairColor: 'Blonde',
            facialHairType: 'BeardMajestic',
            facialHairColor: 'Brown',
            clotheType: 'CollarSweater',
            clotheColor: 'PastelYellow',
            graphicType: 'Skull',
            eyeType: 'Side',
            eyebrowType: 'SadConcernedNatural',
            mouthType: 'Smile',
            skinColor: 'DarkBrown',
        },
    },
    {
        Rank: 4,
        Punten: 2,
        Naam: 'Amiyr Őri',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'LongHairCurly',
            accessoriesType: 'Sunglasses',
            hatColor: 'Gray01',
            hairColor: 'BlondeGolden',
            facialHairType: 'BeardMajestic',
            facialHairColor: 'Platinum',
            clotheType: 'ShirtScoopNeck',
            clotheColor: 'Blue02',
            graphicType: 'Diamond',
            eyeType: 'Default',
            eyebrowType: 'UpDown',
            mouthType: 'Tongue',
            skinColor: 'Light',
        },
    },
    {
        Rank: 5,
        Punten: 2,
        Naam: 'Kai Ríos',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'Eyepatch',
            accessoriesType: 'Blank',
            hatColor: 'PastelRed',
            hairColor: 'Platinum',
            facialHairType: 'MoustacheFancy',
            facialHairColor: 'Black',
            clotheType: 'GraphicShirt',
            clotheColor: 'Blue02',
            graphicType: 'Deer',
            eyeType: 'Cry',
            eyebrowType: 'Angry',
            mouthType: 'Smile',
            skinColor: 'Yellow',
        },
    },
    {
        Rank: 6,
        Punten: 2,
        Naam: 'Hadiza Harðardóttir',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'ShortHairShortFlat',
            accessoriesType: 'Kurt',
            hatColor: 'Blue02',
            hairColor: 'Brown',
            facialHairType: 'Blank',
            facialHairColor: 'Brown',
            clotheType: 'ShirtCrewNeck',
            clotheColor: 'Gray01',
            graphicType: 'Cumbia',
            eyeType: 'Wink',
            eyebrowType: 'DefaultNatural',
            mouthType: 'Twinkle',
            skinColor: 'Yellow',
        },
    },
    {
        Rank: 7,
        Punten: 1,
        Naam: 'Peng Helgason',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'ShortHairShortCurly',
            accessoriesType: 'Wayfarers',
            hatColor: 'Black',
            hairColor: 'Brown',
            facialHairType: 'BeardMajestic',
            facialHairColor: 'BlondeGolden',
            clotheType: 'CollarSweater',
            clotheColor: 'PastelYellow',
            graphicType: 'Bat',
            eyeType: 'Hearts',
            eyebrowType: 'UnibrowNatural',
            mouthType: 'Vomit',
            skinColor: 'DarkBrown',
        },
    },
    {
        Rank: 8,
        Punten: 1,
        Naam: 'Dolores Baldursdóttir',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'LongHairFro',
            accessoriesType: 'Kurt',
            hatColor: 'Pink',
            hairColor: 'Brown',
            facialHairType: 'BeardLight',
            facialHairColor: 'Auburn',
            clotheType: 'ShirtCrewNeck',
            clotheColor: 'PastelOrange',
            graphicType: 'Bat',
            eyeType: 'Wink',
            eyebrowType: 'SadConcerned',
            mouthType: 'Twinkle',
            skinColor: 'Tanned',
        },
    },
    {
        Rank: 9,
        Punten: 1,
        Naam: 'Ragnar Benešová',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'Eyepatch',
            accessoriesType: 'Kurt',
            hatColor: 'Blue02',
            hairColor: 'Black',
            facialHairType: 'Blank',
            facialHairColor: 'Brown',
            clotheType: 'ShirtVNeck',
            clotheColor: 'Blue03',
            graphicType: 'Deer',
            eyeType: 'WinkWacky',
            eyebrowType: 'Angry',
            mouthType: 'Disbelief',
            skinColor: 'Light',
        },
    },
    {
        Rank: 10,
        Punten: 1,
        Naam: 'Mariusz Guzmán',
        Avatar: {
            __typename: 'Avatar',
            avatarStyle: 'Circle',
            topType: 'ShortHairShortWaved',
            accessoriesType: 'Prescription02',
            hatColor: 'PastelBlue',
            hairColor: 'PastelPink',
            facialHairType: 'BeardMajestic',
            facialHairColor: 'Auburn',
            clotheType: 'CollarSweater',
            clotheColor: 'PastelBlue',
            graphicType: 'Skull',
            eyeType: 'Squint',
            eyebrowType: 'Angry',
            mouthType: 'ScreamOpen',
            skinColor: 'Tanned',
        },
    },
];
